### ISSUE TITLE
Docker build issue - No terminals could successfully be created

### ISSUE THREAD

**Issue by Stuart-campbell** [varabyte/kobweb-cli#15]
I have just updated to kobweb-cli 0.9.15 from 0.9.13. The new version works as expected locally but fails when being built with docker.

```
Exception in thread "main" java.lang.IllegalStateException: No terminals could successfully be created. Encountered exceptions:
{java.lang.IllegalStateException: Unable to create a system terminal
```

The docker file is taken from this article https://bitspittle.dev/blog/2023/cloud-deploy but with the cli version updated, and I am doing a static export but it doesn't get that far so don't think that matters.

Great project btw

**Comment by bitspittle** [comment]
Hey, I know this is months late but I guess I missed notifications for issues on this project, very sorry about that!

Did you ever resolve it? Could I see your Dockerfile? Are you using the `--notty` parameter when you call `kobweb`?

**Comment by bitspittle** [comment]
As part of a cleanup, I'm going to close this issue since there hasn't been a reply. However, feel free to ping anytime and we can reopen.

Since you first filed this ticket, there have been a bunch of misc. changes, including the Dockerfile in the linked blog post has been updated a bit. Honestly, nothing that should have caused the "No terminals could successfully be created" message, so I'm a bit stumped... but maybe still worth another try if you haven't in a while.
